language: php

php: 
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  matrix:
    - COMPOSER_ARGS=""
    - COMPOSER_ARGS="--prefer-lowest"

before_install:
  - composer self-update

install:
  - composer update ${COMPOSER_ARGS} --dev --no-interaction

script:
  - phpunit --verbose

sudo: false
